### ISSUE TITLE
prefixed token precesence

### ISSUE THREAD

**Issue by ccorcos** [sighingnow/parsec.py#10] opened 2017-01-05 01:57 UTC
```py
parser = p.string('is not') | p.string('is')
parser.parse('is')
```

I'd expect the first to fail but the second to pass but...

```
Traceback (most recent call last):
  File "src/risk.py", line 207, in <module>
    print parser.parse('is')
  File "/Library/Python/2.7/site-packages/parsec/__init__.py", line 115, in parse
    return self.parse_partial(text)[0]
  File "/Library/Python/2.7/site-packages/parsec/__init__.py", line 128, in parse_partial
    raise ParseError(res.expected, text, res.index)
parsec.ParseError: expected is not at 0:2
```

**Comment by sighingnow** [comment] 2017-01-06 02:28
Notice that `choice` doesn't perform any backtracking when the first parser fails, here the `ParserError` is the  expected behavior.

In your case, you should use the `try_choice` combinator (or operator `^`). When the first parser fails, the second one will start from the original position.

~~~python
In [1]: import parsec as p

In [2]: parser = p.string('is not') ^ p.string('is')

In [3]: parser.parse('is')
Out[3]: 'is'
~~~

**Comment by sighingnow** [comment] 2017-01-06 06:08
Since this isn't a bug of parsec.py library, I'm going to close this issue. Please feel free to reopen if you have any further question. @ccorcos

**Closed by sighingnow** 2017-01-06 06:08 UTC

**Comment by ccorcos** [comment] 2017-01-09 03:58
I see. Any reason why you'd specifically want to use `choice` rather than `try_choice` then?

**Comment by sighingnow** [comment] 2017-01-13 17:16
Hi, @ccorcos  I mush apologize for the delayed response. I implemented the `choice` combinator in this way  because I wanted to keep compatible with the [parsec](http://hackage.haskell.org/package/parsec) package of Haskell.

Parsec does not automatically backtrack for efficiency. **The `choice` combinator will only try the second when the first fails and consume nothing**. Parsec's strategy is essentially LL(1). `try` must save input, unnecessary uses of `try` is very expensive and sometimes to the point of unacceptable performance (exponential time).

Another benefit the `choice` without backtracking is reasonable error messages. A good blog discussing this topic is [Parsec: “try a <|> b” considered harmful](http://blog.ezyang.com/2014/05/parsec-try-a-or-b-considered-harmful/) by Edward Z. Yang. We should reduce the scope of backtracking(`try_choice` operator here).

**Comment by ccorcos** [comment] 2017-01-17 21:38
Hmm. So it can potentially create a memory explosion?
